name: 🧪 Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  release:
    uses: grovegs/workflows/.github/workflows/godot-package-tests.yml@main
    with:
      core-test-project: tests/{{Author(P)}}.{{Name(P)}}.Tests
      godot-test-project: tests/{{Author(P)}}.{{Name(P)}}.Godot.Tests
      global-json-file: global.json
